-- defaults.lua
local DEFAULTS = {
    version = "1.1.0",
    fonts = {
        title             = 30,
        clock             = 42,
        date              = 20,
        fasting           = 18,
        countdown         = 20,
        status            = 10,
        prayer            = 24,
        prayer_next_extra = 14,
        suffix            = 19,
    },
    default_face = "infofont",
    fonts_folder_name = "fonts",
    icon_size = 40,
    spacing = {
        margin          = 10,
        row_gap         = 5,
        prayer_row_gap  = 1,
        separator_width = 8,
        banner_spacing  = 1,
        prayer_row_pad  = 8,
        banner_height   = 60,
    },
    prayer_columns = {
        label_ratio  = 0.32,
        time_ratio   = 0.18,
        suffix_ratio = 0.10,
    },
    settings = {
        font_size_offset_ar = 8,
        font_size_offset_en = 0,
        font_face             = "infofont",
        custom_font_path      = "ReemKufiFun.ttf",
        widget_brightness     = -1,
        language              = "ar",
        time_format           = 12,
        clock_mode            = "live",
        show_hijri            = true,
        show_battery          = true,
        show_wifi             = true,
        show_memory           = true,
        battery_format        = "both",
        auto_show_resume      = true,
        hijri_adjustment      = 0,
        show_fasting_days     = true,
        fasting_reminder_days = 2,
        method                = "Egyptian",
        asr_madhhab           = "Shafi",
        dst_offset            = 0,
        font_sizes = {
            ["ar"] = {
                ["Alkhalil-Round Oplique Right.otf"] = 4,
                ["Astrolabe.ttf"] = 8,
                ["Caveat-Regular.ttf"] = 11,
                ["DARK 2.ttf"] = 10,
                ["Hajeen.ttf"] = 11,
                ["InstaArabi.ttf"] = 11,
                ["Inter-ExtraBold.ttf"] = 8,
                ["Kufam.ttf"] = 8,
                ["Masqool.otf"] = 8,
                ["NotoKufiArabic.ttf"] = 3,
                ["Qahwa Arabic Black.otf"] = 5,
                ["Qashib.ttf"] = 11,
                ["ReemKufiFun.ttf"] = 8,
                ["RobotoCondensed-Bold.ttf"] = 11,
                ["RobotoCondensed-BoldItalic.ttf"] = 11,
                ["RobotoCondensed-Italic.ttf"] = 11,
                ["RobotoCondensed-Regular.ttf"] = 11,
                ["TOX-Geometric.otf"] = 8,
                ["Window Display.otf"] = 1,
                ["ZainFatimiVF.ttf"] = 11,
                ["cfont"] = 8,
                ["infofont"] = 8,
                ["smallinfofont"] = 8,
                ["smalltfont"] = 7,
                ["tfont"] = 7,
                ["x_smallinfofont"] = 8,
            },
            ["en"] = {
                ["Alkhalil-Round Oplique Right.otf"] = 2,
                ["Astrolabe.ttf"] = 5,
                ["Caveat-Regular.ttf"] = 9,
                ["DARK 2.ttf"] = 10,
                ["Hajeen.ttf"] = 8,
                ["InstaArabi.ttf"] = 8,
                ["Inter-ExtraBold.ttf"] = 6,
                ["Kufam.ttf"] = 6,
                ["Masqool.otf"] = 6,
                ["NotoKufiArabic.ttf"] = 1,
                ["Qahwa Arabic Black.otf"] = 3,
                ["Qashib.ttf"] = 8,
                ["ReemKufiFun.ttf"] = 5,
                ["RobotoCondensed-Bold.ttf"] = 9,
                ["RobotoCondensed-BoldItalic.ttf"] = 9,
                ["RobotoCondensed-Italic.ttf"] = 9,
                ["RobotoCondensed-Regular.ttf"] = 8,
                ["TOX-Geometric.otf"] = 5,
                ["Window Display.otf"] = 2,
                ["ZainFatimiVF.ttf"] = 9,
                ["cfont"] = 8,
                ["infofont"] = 8,
                ["smallinfofont"] = 8,
                ["smalltfont"] = 5,
                ["tfont"] = 5,
                ["x_smallinfofont"] = 8,
            },
        },
    },
    region_methods = {
        ["Egypt"]                = "Egyptian",
        ["Libya"]                = "Egyptian",
        ["Sudan"]                = "Egyptian",
        ["Iraq"]                 = "Egyptian",
        ["Syria"]                = "Egyptian",
        ["Lebanon"]              = "Egyptian",
        ["Palestine"]            = "Egyptian",
        ["Jordan"]               = "Egyptian",
        ["Algeria"]              = "Egyptian",
        ["Tunisia"]              = "Egyptian",
        ["Morocco"]              = "Egyptian",
        ["Saudi Arabia"]         = "UmmAlQura",
        ["Yemen"]                = "UmmAlQura",
        ["UAE"]                  = "UmmAlQura",
        ["United Arab Emirates"] = "UmmAlQura",
        ["Qatar"]                = "UmmAlQura",
        ["Bahrain"]              = "UmmAlQura",
        ["Kuwait"]               = "UmmAlQura",
        ["Oman"]                 = "UmmAlQura",
        ["Pakistan"]             = "Karachi",
        ["India"]                = "Karachi",
        ["Bangladesh"]           = "Karachi",
        ["Afghanistan"]          = "Karachi",
        ["United States"]        = "ISNA",
        ["USA"]                  = "ISNA",
        ["Canada"]               = "ISNA",
        ["Iran"]                 = "Tehran",
        ["Turkey"]               = "MWL",
        ["Malaysia"]             = "MWL",
        ["Indonesia"]            = "MWL",
        ["United Kingdom"]       = "MWL",
        ["Germany"]              = "MWL",
        ["France"]               = "MWL",
    },
}

local LAYOUT_MATRIX = {
    ["en"] = {
        header_order = {
            "title", "clockline", "combined_date_line",
            "fastingline", "statusline", "divider", "prayers",
            "countdownline",
        },
        status_row        = { "battery", "wifi", "memory" },
        status_cell_order = { "label", "ssep", "value" },
        prayer_row        = { "icon", "psep1", "plabel", "psep2", "ptime", "psep3", "psuffix" },
        title_align         = "center",
        clock_align         = "center",
        combined_date_align = "center",
        status_align        = "center",
        countdown_align     = "center",
        prayer_align        = "center",
        dsep_text         = ",",
        date_divider_text = " | ",
        psep1_text        = "  ",
        psep2_text        = "  ",
        psep3_text        = " ",
        ssep_text         = ":",
        font_how_to_add = "How to add fonts",
    },
    ["ar"] = {
        header_order = {
            "title", "clockline", "combined_date_line",
            "fastingline", "statusline", "divider", "prayers",
            "countdownline",
        },
        status_row        = { "memory", "wifi", "battery" },
        status_cell_order = { "value", "ssep", "label" },
        prayer_row        = { "psuffix", "psep3", "ptime", "psep2", "plabel", "psep1", "icon" },
        title_align         = "center",
        clock_align         = "center",
        combined_date_align = "center",
        status_align        = "center",
        countdown_align     = "center",
        prayer_align        = "center",
        dsep_text         = "،",
        date_divider_text = " | ",
        psep1_text        = "  ",
        psep2_text        = "  ",
        psep3_text        = " ",
        ssep_text         = ":",
        font_how_to_add = "كيفية إضافة الخطوط",
    },
}

return {
    DEFAULTS = DEFAULTS,
    LAYOUT_MATRIX = LAYOUT_MATRIX,
}